# Copyright (C) 2024 Alexandre Nicolaie (xunleii@users.noreply.github.com)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#         http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ----------------------------------------------------------------------------
---
name: ðŸ§ª Run coverage
on:
  push:
    branches: [main]
    paths:
      - .github/workflows/push.rust.yaml
      - .github/workflows/workflow_call.rust.coverage.yaml
      - .github/workflows/workflow_call.rust.test.yaml
      - src/**
      - tests/**

permissions: {}

jobs:
  rust-test:
    name: ðŸ§ª
    uses: ./.github/workflows/workflow_call.rust.coverage.yaml
